spring:
  application:
    name: ms-users-main
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
jwt:
  secret: accionesElBosque20251
stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  public-key: ${STRIPE_PUBLIC_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
exchange:
  api:
    key: ${EXCHANGE_API_KEY}



